# --- !Ups

create table "flights" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "source" varchar not null,
  "destination" varchar not null,
  "carrier" varchar not null,
  "dateOfTravel" varchar not null,
  "dateOfPriceFall" varchar not null,
  "predictedPrice" int not null,
  "latitude" varchar not null,
  "longitude" varchar not null,
  "distance" varchar not null,
  "seats" int not null
);

# --- !Downs

drop table "flights" if exists;
